### ISSUE TITLE
大佬能不能弄个避免社会性死亡的开关

### ISSUE THREAD

**Issue by Snakebinp** [YukinoShary/Pixiv-Wallpaper-for-Windows-10#1]
qql

**Comment by YukinoShary** [comment]
"避免社会性死亡的开关"指的是关闭r-18么？其实WebAPI模式以及PixivCS模式都是默认筛选掉了r-18标签的插画的，不会有任何带R-18 tag的插画出现（不会真的有人用r-18插画做壁纸吧？不会吧？）当然普通的涩图因为没有r-18标签也是照样会有的。
