### ISSUE TITLE
登陆后没有载图

### ISSUE THREAD

**Issue by SettingDust** [YukinoShary/Pixiv-Wallpaper-for-Windows-10#4]
- [x] 登陆后会显示
![image](https://user-images.githubusercontent.com/19922286/119431888-f70ab800-bd45-11eb-9721-c63af5c20cda.png)
- [x] 登陆后没有下载任何图片，点击下一张没有反应，点击刷新崩溃

```
故障存储段 2204635896850678902，类型 5
事件名称: MoAppCrash
响应: 不可用
Cab ID: 0

问题签名:
P1: 63929Shary.PixivWallpaperforWindows10_1.7.2.0_x64__hzhgmpxe3vqfr
P2: praid:App
P3: 1.0.0.0
P4: 60a533cf
P5: combase.dll
P6: 10.0.19041.928
P7: c94441ae
P8: 80004003
P9: 0000000000086256
P10: 
```

```
错误应用程序名称: Pixiv_Wallpaper_for_Windows_10.exe，版本: 1.0.0.0，时间戳: 0x60a533cf
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.964，时间戳: 0x812662a7
异常代码: 0xc000027b
错误偏移量: 0x000000000010b39c
错误进程 ID: 0x4f3c
错误应用程序启动时间: 0x01d7510f3de69363
错误应用程序路径: C:\Program Files\WindowsApps\63929Shary.PixivWallpaperforWindows10_1.7.2.0_x64__hzhgmpxe3vqfr\Pixiv_Wallpaper_for_Windows_10.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: 38406c77-4f10-4f2a-97b7-82010cd8345d
错误程序包全名: 63929Shary.PixivWallpaperforWindows10_1.7.2.0_x64__hzhgmpxe3vqfr
错误程序包相对应用程序 ID: App
```

**Comment by YukinoShary** [comment]
感谢你提交问题反馈。
1、关于切换应用的选项框，这个选择“是”就可以了。这个是webview登录之后回传的URI进行应用激活处理。
2、如果你能够成功进入到应用主界面，请切换到设置页点击“浏览本地文件夹”按钮，在文件夹中可以找到log.txt。请把其中的内容贴到此issue中以帮助我更快地找到问题发生的原因。如果log内容太多，适量地贴上早期的部分log即可。最底部的即为最早记录的内容。

**Comment by SettingDust** [comment]
> 感谢你提交问题反馈。
> 1、关于切换应用的选项框，这个选择“是”就可以了。这个是webview登录之后回传的URI进行应用激活处理。
> 2、如果你能够成功进入到应用主界面，请切换到设置页点击“浏览本地文件夹”按钮，在文件夹中可以找到log.txt。请把其中的内容贴到此issue中以帮助我更快地找到问题发生的原因。如果log内容太多，适量地贴上早期的部分log即可。最底部的即为最早记录的内容。

1. 每次打开都要登录吗？
2. 没有 log 文件

**Comment by YukinoShary** [comment]
1、只有第一次登录需要通过webview访问pixiv输入账号密码登录，在一次登录成功后应用会保存refreshToken之后都使用refreshToken发送登录请求而不会跳转pixiv
2、应用内点击“下一张插画”发送http请求之后就会记录请求log了。还有关于log的描述刚才说错了，顶部的才是最早的记录。

**Comment by YukinoShary** [comment]
如果登录成功，log中是可以看到accessToken ，refreshToken以及expire time之类的http content的

**Comment by SettingDust** [comment]
> 1、只有第一次登录需要通过webview访问pixiv输入账号密码登录，在一次登录成功后应用会保存refreshToken之后都使用refreshToken发送登录请求而不会跳转pixiv
> 2、应用内点击“下一张插画”发送http请求之后就会记录请求log了。还有关于log的描述刚才说错了，顶部的才是最早的记录。

但是我每次都要点击以此账号继续，而且没有任何log

**Comment by YukinoShary** [comment]
你的描述应用似乎在登录过程中就出现了问题，我目前无法在自己的电脑上复现此问题。根据你提供的错误提示，有可能是你的系统中KERNELBASE.dll文件错误导致的问题。你可以尝试一下这个方法修复KERNELBASE.dll
https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/programs-crash-error-fault-module-kernelbasedll/9fe5d2e7-79d0-42c1-b8dc-51ed8d70f749

**Comment by SettingDust** [comment]
> 你的描述应用似乎在登录过程中就出现了问题，我目前无法在自己的电脑上复现此问题。根据你提供的错误提示，有可能是你的系统中KERNELBASE.dll文件错误导致的问题。你可以尝试一下这个方法修复KERNELBASE.dll
> https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/programs-crash-error-fault-module-kernelbasedll/9fe5d2e7-79d0-42c1-b8dc-51ed8d70f749

我认为与此无关，我之后有时间会试试 clone debug 一下

**Comment by SettingDust** [comment]
试了一下，登陆失败，pixiv 变量为空，PixivCS 报错，"Authentication failed because the remote party has closed the transport stream.，代理没问题，原因应该是代理的同时绕过了SNI导致服务端安全验证不过，拒绝了请求。
https://github.com/YukinoShary/pixivcs/blob/master/Utils/Utilities.cs#L18 抛出错误的函数
https://github.com/YukinoShary/pixivcs/blob/master/PixivBaseAPI.cs#L369 调用点

**Comment by SettingDust** [comment]
我在发送登录请求的位置断点，然后关掉代理，再继续执行就可以正常登录、生成日志。确认是因为代理+SNI的问题，最好有一个开关选择是否使用。
PixivCS代码里面只提供了绕过SNI的方法，但是登录使用网页登录又必须要代理，有些矛盾

**Comment by SettingDust** [comment]
进入设置界面后，需要再开启代理以下载 图片，不然只能请求web api，无法下载图片，开启代理后图片正常下载，不过这工序有点麻烦orz

**Comment by SettingDust** [comment]
现在可以正常登录的操作是 
1. 启动，点击以此账号继续/登录
2. 在点击跳转应用的确认之前断掉代理，点击确认
3. 立刻启用代理，否则第一张图下载会失败，或者启用后点击刷新
4. 应用

**Comment by YukinoShary** [comment]
PixivCS是由别人写的库，后来pixiv方面更改了登录api，使用OAuth2的codechallenge方式进行登录因此原本的post账号密码的连接方式就失效了。但是我之前就一直用着pixivCS这个库，懒得重改所有的api所以就只是在PixivCS绕过SNI的通信方法的基础上加入了codechallenge相关的支持。我现在会想办法改一改pixivCS的通信方式，改为正常的连接。
只有第一次登录是需要webview所以载图没问题的话你可以开着代理进行refreshToken的登录。

**Comment by SettingDust** [comment]
或者可以使用 pixiv.cat 代理一下图片，就不需要切换代理了

**Comment by YukinoShary** [comment]
我认为你之前说的是对的，既然在首次登录中就需要通过代理连接pixiv，之后的行为又用各种非代理手段连接会显得有些鸡肋。所以我是打算修一修正常连接的方法直接套用了。或者说这个图片代理的方式我会考虑在之后的更新中作为一项可选内容放在设置中。

**Comment by SettingDust** [comment]
> 我认为你之前说的是对的，既然在首次登录中就需要通过代理连接pixiv，之后的行为又用各种非代理手段连接会显得有些鸡肋。所以我是打算修一修正常连接的方法直接套用了。或者说这个图片代理的方式我会考虑在之后的更新中作为一项可选内容放在设置中。

可以不代理就进去是好的，但是不代理就不能下载图片，而且代理了不让进就有点难受了XD
catch 到异常就换个方法重发一次请求，也可以

**Comment by YukinoShary** [comment]
理论上来说用绕过SNI的方式是可以载图，只是特别慢而已。印象中联通4G载图速度是比较快的。至于webview那块的免代理我暂时不考虑做了。那我之后就只把pixiv.cat的代理开关加入设置项中好了。

**Comment by YukinoShary** [comment]
我折腾了一下午发现有概率会撞人机验证。我自己从之前去SNI的方法改用普通连接方法后因为请求的服务器不同也出现了人机验证，结果卡了老半天我还以为是普通连接的请求写得有问题。退出登录重新输入账号密码后解决了问题。不过这个还是挺玄乎的，不知道什么时候可能就登不上了。

**Comment by YukinoShary** [comment]
我有十足的信心保证我把连接方式改为普通连接后，所有人都需要重新进行登录。而且是需要重新输入账号密码的登录。

**Comment by SettingDust** [comment]
API 的访问也不能使用代理，所以获取新图片要先关闭代理hhhhh

**Comment by SettingDust** [comment]
> 我有十足的信心保证我把连接方式改为普通连接后，所有人都需要重新进行登录。而且是需要重新输入账号密码的登录。

可以默认开启 SNI 进行连接吧，连接不上再关闭:D

**Comment by YukinoShary** [comment]
> API 的访问也不能使用代理，所以获取新图片要先关闭代理hhhhh

是指pixiv.cat不能使用代理？还是说海外连接都无法使用pixiv.cat?

**Comment by SettingDust** [comment]
> > API 的访问也不能使用代理，所以获取新图片要先关闭代理hhhhh
> 
> 是指pixiv.cat不能使用代理？还是说海外连接都无法使用pixiv.cat?

API 是指 pixiv 返回 json 的 API，比如推荐图片，但是获取到 json 之后，想要再下载图还要开代理

**Comment by YukinoShary** [comment]
我刚才推上去了一些更新，目前还不打算更改商店中的版本。我改了登录请求错误之后的逻辑，如果是第一次登录时失败会返回pixiv登录页，这时候就已经切成普通的请求模式了。你可以拉一下github的代码自己编译，可以不用商店的版本。pixivCS没改什么东西，只是可以把普通模式的log记录下来而已。0.8.6版本就只是改了这些而已，你也可以去我的pixivCS项目分支里拉一下代码。
至于pixiv.cat代理，我不想在pixivCS库里面写这个，所以要在应用里面再单独写一个web api的请求模块，这个先咕一咕，有时间再弄了。

**Comment by SettingDust** [comment]
> 我刚才推上去了一些更新，目前还不打算更改商店中的版本。我改了登录请求错误之后的逻辑，如果是第一次登录时失败会返回pixiv登录页，这时候就已经切成普通的请求模式了。你可以拉一下github的代码自己编译，可以不用商店的版本。pixivCS没改什么东西，只是可以把普通模式的log记录下来而已。0.8.6版本就只是改了这些而已，你也可以去我的pixivCS项目分支里拉一下代码。
> 至于pixiv.cat代理，我不想在pixivCS库里面写这个，所以要在应用里面再单独写一个web api的请求模块，这个先咕一咕，有时间再弄了。

我不太明白怎么引用 Git 仓库作为项目的编译时依赖，我是 NuGet 引用的你的库，但是看起来没更新

**Comment by YukinoShary** [comment]
你把pixivCS库也编译了就好了。编译好的nuget包直接拿给项目引用。懒的话直接改一改引用改回nuget上面的0.8.4版本也行
