### ISSUE TITLE
2021/12/13 登陆问题

### ISSUE THREAD

**Issue by Enemy-C** [YukinoShary/Pixiv-Wallpaper-for-Windows-10#8]
2021/12/13 突发，登陆页面没有账号密码直接登录的选项，仅剩通过苹果、微博、谷歌等第三方账号登陆的选项

**Comment by YukinoShary** [comment]
问题似乎出在WebView上。目前使用的WebView版本还是EdgeHTML（旧版Edge浏览器）的引擎。我试着用新版Edge（Chromium殷勤）做WebView之后登录页面是可以正常显示账号密码栏。但是目前新版Edge只支持新的平台WinUI3，旧平台UWP已经是被微软抛弃了。然而新平台WinUI3又还有许多地方没有完善，很多功能用不了。微软这种态度让我也不是很想修这个问题……这段时间可能是不会有更新了。

**Comment by moonheart** [comment]
我也遇到这个问题, 只好在网页版上去绑了个 google 帐号, 然后到应用里面用 google 登录;
但是登录成功之后直接白屏了.
关闭之后重启, 就会进入一个没有登录框的登录页面.

已开启代理; 已开启 UWP loopback

**Comment by YukinoShary** [comment]
@moonheart @Enemy-C 改好了WinUI3版本的确认可以用了。晚上我回去编译打包一下会把旁加载包和证书发到这个repo的release里面，微软商店上面的应用我下架暂时不打算更新了。（WinUI3用不了Acrylic材质，毛玻璃没有了并且可能还有更多原本的feature不支持）

**Comment by moonheart** [comment]
新的 pre-release 可以登录并使用了

**Comment by Enemy-C** [comment]
新版本已经可以使用，感谢您的付出！
