### ISSUE TITLE
Windows 10 21H1无法安装

### ISSUE THREAD

**Issue by yellowko** [YukinoShary/Pixiv-Wallpaper-for-Windows-10#9]
证书已安装，在安装应用时提示

> 应用安装失败，错误消息: 由于程序包 63929Shary.PixivWallpaperWinUI3_2.0.3.0_x64__98mah9224qs2t 与设备不兼容，Windows 无法安装该程序包。该程序包要求 Windows.Universal 设备系列运行操作系统版本 10、0、20348、0 或更高版本。该设备当前运行的操作系统版本为 10、0、19043、1586。 (0x80073cfd)

看了下代码，目标平台设置为了Windows 11 ([22000](https://github.com/YukinoShary/Pixiv-Wallpaper-for-Windows-10/blob/c4075cfb66217af0a1d6807a4f92576aacdb329f/Pixiv_Wallpaper_WinUI/Pixiv_Wallpaper_WinUI.csproj#L14))，最低要求平台是Windows Server 2022([20348](https://github.com/YukinoShary/Pixiv-Wallpaper-for-Windows-10/blob/c4075cfb66217af0a1d6807a4f92576aacdb329f/Pixiv_Wallpaper_WinUI/Pixiv_Wallpaper_WinUI.csproj#L15))，而Windows 10 21H1(19043)，所以不满足安装条件。不知道是工程设置错了还是[README](https://github.com/YukinoShary/Pixiv-Wallpaper-for-Windows-10/blob/master/README.md#:~:text=UWP%20APP%EF%BC%8C%E9%9C%80%E8%A6%81%E5%9C%A8-,Windows%2010%202104,-%E4%BB%A5%E4%B8%8A%E7%9A%84%E7%89%88%E6%9C%AC)里写错了。

**Comment by YukinoShary** [comment]
是Windows 10 LTSC是吧？LTSC的版本号是不太一样，稍微落后于家庭版和专业版。我自己试过了把项目平台设置支持调低到2004版本但是21H1的LTSC系统上也依旧无法安装，无法支持WinUI的部分.NET依赖

**Comment by yellowko** [comment]
不是啊，我的是家庭版的

> 版本	Windows 10 家庭中文版
> 版本号	21H1
> 安装日期	‎2021/‎12/‎10
> 操作系统内部版本	19043.1586
> 体验	Windows Feature Experience Pack 120.2212.4170.0

**Comment by YukinoShary** [comment]
我编译了一个新的支持2004版本的给你试试看。

**Comment by yellowko** [comment]
可以了，谢谢大佬。
